version: '2'
services:
  app:
    build: .
    depends_on:
      - mongo
    volumes:
      - .:/data/hackathon
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
      - MONGOLAB_URI=mongodb://mongo:27017/test
  mongo:
    restart: always
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
